### ISSUE TITLE
Including fcover.pdf in gitt.pdf output

### ISSUE THREAD

**Issue by jonasbb** [cbx33/gitt#16]
There is a nice cover for GITT in images/source/fcover.pdf.

The current way to include this in the output is with the makefile, but this breaks the links and is unnecessary because LaTeX can handle this also.

There are multiple ways how to include it:
- The first page is fcover.pdf, the third page is the old title.
- The first page is fcover.pdf, the third page is the old title but the old title gets page number 1.
- The first page is fcover.pdf, the old title will be removed.

I prefer the first or the second way but the first at most.

**Comment by jonasbb** [comment]
@cbx33 @godbyk:
Have you read this?

**Comment by godbyk** [comment]
It sounds like you have two questions:  (1) what's the best way to include a PDF title page, and (2) what's the preferred arrangement of the title page and half title page.

(1) The easiest solution is probably to include the PDF using \includegraphics.  I can write the code for this if you like.

(2) The answer to this one depends on if you're thinking of the final PDF as a printed book or as something to be read on-screen.

For on-screen reading, I would probably only include the one title page.  There's no need to force readers to scroll through extra pages to get to the content of the book.  (Having said that, we can direct the PDF viewer to open the PDF at a certain page number and that will mitigate some of this concern.)

For printing in a book, I'd recommend having a half title page (sometimes referred to as a bastard title page) first (page i, but the page number isn't printed).  This half title page serves the purpose of taking the brunt of any mistreatment by the cover.  The full title page (page iii) would follow.

The half title page is a pared down version of the full title page.  The half title page usually contains only the main title of the book (less any subtitle).

The full title page contains the full title of the book, the author's name, publisher's name, etc.

Does that answer your question(s)?

**Comment by jonasbb** [comment]
Yes this answers my question.
But I would not use \includegraphics because you can get trouble with full site images.

The use of pdfpages and \includepdf{} is easier. I have made you a example code: here #17

**Comment by cbx33** [comment]
Been out of the loop for the last week or so, but will check into this again as soon as I have some spare cycles

**Comment by jonasbb** [comment]
No problem. This is not so important. I know that people do not always have much time for leisure projects.

**Comment by jonasbb** [comment]
Can be closed because cbx33 tries to implement it.
