### ISSUE TITLE
Problem with page numbering at section start

### ISSUE THREAD

**Issue by jonasbb** [cbx33/gitt#18]
On the begining page of Week 1 the page numbers are at the bottom middle of the page. In the following pages the numbers are on the top left or top right corner.

I think for a more consistent look of the book the bottom numbers should move to the top corners.

PS: Nice new testing design

**Comment by godbyk** [comment]
The placement of the page number for the chapter openings will ultimately depend on the design of the chapter heading.  Once we've settled on the chapter heading, we can look at the placement of the page number (if we want it to appear at all).

**Comment by cbx33** [comment]
To be honest, many books do it this way.  I am happy with the page number at the bottom of the page on a section start
