### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by mdboom** [cbx33/gitt#2]
Any idea what's causing this?

<pre>
> make
pdflatex gitt.tex
This is pdfeTeX, Version 3.141592-1.21a-2.2 (Web2C 7.5.4)
entering extended mode
(./gitt.tex
LaTeX2e <2003/12/01>
Babel <v3.8d> and hyphenation patterns for american, french, german, ngerman, b
ahasa, basque, bulgarian, catalan, croatian, czech, danish, dutch, esperanto, e
stonian, finnish, greek, icelandic, irish, italian, latin, magyar, norsk, polis
h, portuges, romanian, russian, serbian, slovak, slovene, spanish, swedish, tur
kish, ukrainian, nohyphenation, loaded.
(/usr/share/texmf/tex/latex/memoir/memoir.cls
Document Class: memoir 2004/04/05 v1.61 configurable document class
(/usr/share/texmf/tex/latex/memoir/mem12.clo)
(/usr/share/texmf/tex/latex/memoir/mempatch.sty))

******************************************************
Stock height and width: 597.50787pt by 421.10078pt
Top and edge trims: 0.0pt and 0.0pt
Page height and width: 597.50787pt by 421.10078pt
Text height and width: 490.5pt by 305.0pt
Spine and edge margins: 61.45805pt and 54.34486pt
Upper and lower margins: 54.34486pt and 52.66301pt
Headheight and headsep: 14.0pt and 19.8738pt
Footskip: 30.0pt
Columnsep and columnseprule: 10.0pt and 0.0pt
Marginparsep and marginparwidth: 7.0pt and 51.0pt
******************************************************

(/usr/share/texmf/tex/latex/graphics/graphicx.sty
(/usr/share/texmf/tex/latex/graphics/keyval.sty)
(/usr/share/texmf/tex/latex/graphics/graphics.sty
(/usr/share/texmf/tex/latex/graphics/trig.sty)
(/usr/share/texmf/tex/latex/graphics/graphics.cfg)
(/usr/share/texmf/tex/latex/graphics/pdftex.def)))
(/usr/share/texmf/tex/latex/float/float.sty

! LaTeX Error: Command \newfloat already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.68       {}}}
               
? 
</pre>

**Comment by cbx33** [comment]
Interesting....I will investigate this tonight - I'm not sure what is going on there, I'm fairly new to latex.  You can try to do a make html, which will give you the html version to check.  What distro is this on?

**Comment by mdboom** [comment]
This is on RHEL5.

**Comment by cbx33** [comment]
OK, I'll ask one of my latex buddies....read gurus

**Comment by cbx33** [comment]
Please pull and try again - removed a float like which could have been offending

**Comment by cbx33** [comment]
Can you confirm if this issue still exists?

**Comment by mdboom** [comment]
Looks good now.  Thanks.

**Comment by cbx33** [comment]
Resolved
