### ISSUE TITLE
Can't make pdf on Linux Mint x64

### ISSUE THREAD

**Issue by goranc** [cbx33/gitt#22]
After install latex dependencies on Linux Mint Helena - x64 Edition, I can't make pdf.
After some processing shell execution stopped on prompt.
## Lines before ? prompt:

pdfTeX warning: pdflatex (file ./images/fcover-new.pdf): PDF inclusion: Page Gr
oup detected which pdfTeX can't handle. Ignoring it.
{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}>] [2](/usr/share/texmf/tex/latex/lm/ot1lmr.fd)
(/usr/share/texmf-texlive/tex/latex/microtype/mt-cmr.cfg)
(/usr/share/texmf/tex/latex/lm/omllmm.fd)
(/usr/share/texmf/tex/latex/lm/omslmsy.fd)
(/usr/share/texmf/tex/latex/lm/omxlmex.fd) [3] [4] (./gitt.toc [5] [6] [7]
Overfull \hbox (1.5877pt too wide) detected at line 110
 \OT1/lmss/bx/n/12 117

Overfull \hbox (1.5877pt too wide) detected at line 113
 \OT1/lmss/bx/n/12 127

Overfull \hbox (1.5877pt too wide) detected at line 127
 \OT1/lmss/bx/n/12 147

Overfull \hbox (1.5877pt too wide) detected at line 132
 \OT1/lmss/bx/n/12 151
[8]
Overfull \hbox (1.5877pt too wide) detected at line 149
 \OT1/lmss/bx/n/12 173

Overfull \hbox (1.5877pt too wide) detected at line 153
 \OT1/lmss/bx/n/12 181

Overfull \hbox (1.5877pt too wide) detected at line 166
 \OT1/lmss/bx/n/12 201

Overfull \hbox (1.5877pt too wide) detected at line 169
 \OT1/lmss/bx/n/12 203
) [9] (./intro.tex [10]
! Undefined control sequence.
<argument> \memUChead 
                      {\f@rhdr }
l.3 \chapter{Introduction}

?

**Comment by cbx33** [comment]
I will see if we can find out why this is not working for you

**Comment by godbyk** [comment]
goranc, I'd suggest running 'make clean' and then giving it another shot.  Sometimes the old .aux files can get in the way. 

If that doesn't fix it, let me know and I'll help you troubleshoot the problem.

**Comment by cbx33** [comment]
goranc - Is this still an issue?

**Comment by goranc** [comment]
I upgraded my comp with LinuxMint 9 (Ubuntu 10.04 LTS Desktop) 64bit and new
SSD drive.
Everything is working now on new OS, I successfully made gitt pdf document.

Thanks for support.

g.c.

2011/8/30 cbx33 <
reply@reply.github.com>

**Comment by cbx33** [comment]
Awesome - will close issue now
