### ISSUE TITLE
Possibly change the main font and trench font

### ISSUE THREAD

**Issue by cbx33** [cbx33/gitt#28]
Make it so we can choose fonts easier
Possibly make the main font serif, and then make the trenches font match

**Comment by godbyk** [comment]
The main font has been changed to Linux Libertine and the Trenches font has been changed to Fontin Sans for the moment.  How do you think these fonts look?

**Comment by cbx33** [comment]
Linux Libertine looks great, not sure about Fontin Sans.  Have changed to LMSans10 at the moment which I quite like.  Will try it again in a few days to see what my eyes think then.

**Comment by cbx33** [comment]
Fonts looks good now - closing issue
