### ISSUE TITLE
$ symbol looks odd in code sections in dev branch design

### ISSUE THREAD

**Issue by cbx33** [cbx33/gitt#30]
$ symbol looks odd in code sections in dev branch design

**Comment by godbyk** [comment]
Does it look odd with the DejaVu Sans Mono font that we're using now?

What do you think is odd about it?  How would you like it to appear?

**Comment by cbx33** [comment]
I think the main thing is it doesn't get bolded like the rest of the characters

**Comment by godbyk** [comment]
I wonder if you're using a different font than I am.  Here's how it looks for me:

![Code example](http://i.imgur.com/BgdOP.png)

**Comment by cbx33** [comment]
Seems like my Tex implementation will try updating later
