### ISSUE TITLE
~ looks odd in code sections of dev design branch

### ISSUE THREAD

**Issue by cbx33** [cbx33/gitt#31]
~ looks odd in code sections of dev design branch

**Comment by godbyk** [comment]
Does it look odd with the DejaVu Sans Mono font that we're using now?

What do you think is odd about it?  How would you like it to appear?

**Comment by cbx33** [comment]
It looks odd....too high in the line

**Comment by godbyk** [comment]
I wonder if you're using a different font than I am.  Here's how it looks for me:

![Code example](http://i.imgur.com/BgdOP.png)

**Comment by cbx33** [comment]
It must be because of old Tex on my machine - will try updating later
