### ISSUE TITLE
Automatically-updated PDF - link?

### ISSUE THREAD

**Issue by rpavlik** [cbx33/gitt#38]
I've added a job to my continuous integration server to poll the repo for changes hourly and upload the PDF to a web server here: http://www.hci.iastate.edu/~rpavlik/doxygen/git-in-the-trenches/

I'm wondering if you would want to link to that, or if there's some other place I can set up my build system (Jenkins) to send it to - I can send stuff using at least SCP or Git, and possibly other methods, whatever works best for you. Let me know!

**Comment by cbx33** [comment]
It would be very cool to have this building it every hour.
I am wondering also about how to "publish" the site - hopefully we can chat about this later.

**Comment by cbx33** [comment]
https://github.com/cbx33/tempo - holds all PDF, MOBI and EPUB
