### ISSUE TITLE
Building HTML version

### ISSUE THREAD

**Issue by rpavlik** [cbx33/gitt#40]
I'd like to add an HTML build to my autobuilder, but I can't quite figure it out entirely.  A few possible issues/bugs:
- I see that `make site` and `make web` both exist, and are different - is this a bug?
- clean doesn't depend on cleansite
- cleansite doesn't depend on cleanimages
- site doesn't depend on the python script

I've addressed these in an improved makefile - will be pull requested soon.

Also...
- In the generated `site` folder, the only link that works is the "read now", and the "slide1" image is missing. 
- It looks like the python script is supposed to replace the next/prev placeholders, but it doesn't seem to be doing that.

I've uploaded the "site" directory to my server space from the autobuilder for now - you're welcome to take a look and see if there's some improvement that can be made.

http://www.hci.iastate.edu/~rpavlik/doxygen/git-in-the-trenches/site/

**Comment by cbx33** [comment]
Hey thanks for looking at it
Remember this is all WIP at the moment :)
But yes, the idea is to do 
`make html`
`make htmlimages`
This should build everything that is required in the `site` folder.
I'm just sitting down to take a look at what needs doing so allow me a few minutes to look through your pull requests
