### ISSUE TITLE
Change arrows direction in commit history graphs ?

### ISSUE THREAD

**Issue by zigarn** [cbx33/gitt#48]
The convention for arrows is from pointer to pointed.
It is OK for commit -> tree -> blob, but in commit history graphs the arrows are in 'time' direction C1 -> C2 -> C3.
Shouldn't it be in C1 <- C2 <- C3 direction, like in progit book  and to be closer to a real DAG (http://stackoverflow.com/questions/2676302/arrows-direction-in-progit-book) ?

**Comment by cbx33** [comment]
Good point. I guess my arrows were showing chronological order and not
relationship. I guess each is valid in their own way. Which one makes more
sense...hmm...i will have a think. thank you so much for bringing this to my
attention.

Pete
On 31 Aug 2011 16:14, "zigarn" <
reply@reply.github.com>
wrote:

**Comment by cbx33** [comment]
Leaving this as is for now - will revisit in the second edition
