### ISSUE TITLE
wording correction

### ISSUE THREAD

**Issue by ericlake** [cbx33/gitt#49]
In the Introduction the last line says "With the introduction over, let’s first go through a quick setup guide and then find out why Tamagoyaki Inc even **need** a version control system in the first place."

This may be nit picking but shouldn't it say "even **needs** a version control system in the first place."?

**Comment by cbx33** [comment]
You are probably right my friend :) I will correct in the next batch of corrections.

**Comment by dsas** [comment]
This was fixed in 2c362b3

**Comment by cbx33** [comment]
Yup - confirmed

**Comment by godbyk** [comment]
There may be other occurrences of the same issue throughout the book.  In American English, corporations (Tamagoyaki Inc) are considered singular nouns.  In contrast, British English considers them to by plural nouns.  You should decide which variant of English you prefer to use and stick with it throughout the book.

**Comment by cbx33** [comment]
Did not know this :) Thanks godbyk
