### ISSUE TITLE
.mobi Version Skips Around

### ISSUE THREAD

**Issue by lolajl** [cbx33/gitt#51]
I downloaded the .mobi version, and installed on Kindle. There seems to be a problem with the flow. I will start a chapter, for instance, Chapter 1, page through it and then suddenly it pauses for a long time, then skips to the end of the book. The problem seems to be the callback sections. When I have more time I'll go back and make notice of where the skip-ahead occurs; it isn't just in one chapter, but at spots throughout the book.

**Comment by cbx33** [comment]
Thanks for the comment Ill take a look later
On 14 Jan 2012 12:26, "Lola J. Lee Beno" <
reply@reply.github.com>
wrote:

**Comment by bskelton** [comment]
I have the same issue. First occurance for me is around 5%

**Comment by cbx33** [comment]
Interesting. These were created with calibre from a nice clean html.
On 15 Jan 2012 14:14, "psuede" <
reply@reply.github.com>
wrote:

**Comment by cbx33** [comment]
It actually looks like it is skipping where the images occur. I will have to take a deeper look into this.

**Comment by cbx33** [comment]
This has now been resolved and the mobi seems to work fine on the kindle I tested on

**Comment by cbx33** [comment]
http://cbx33.github.com/gitt/

Let me know if it works
On 22 Feb 2012 23:45, "Lola J. Lee Beno" <
reply@reply.github.com>
wrote:

**Comment by bskelton** [comment]
Tried it last night and everything looks good

**Comment by cbx33** [comment]
Awesome :)

**Comment by lolajl** [comment]
Working for me now.
