### ISSUE TITLE
TeX percent-sign doesn't translate to HTML

### ISSUE THREAD

**Issue by Gumnos** [cbx33/gitt#52]
In Chapter 1, the source reads "This is all due to the fact that Git does 99\% of all of its operations locally." But the generated HTML truncates at that token, leaving the text as "This is all due to the fact that Git does 99When a repository is cloned..."  I trust that the other outputs correctly display the "99%" as desired, so it may be something in your TeX-to-HTML converter.

**Comment by Gumnos** [comment]
(see http://cbx33.github.com/gitt/chap1-2.html for the output in question)

**Comment by Gumnos** [comment]
Same goes similarly for the afterhours2.tex where "Git will inspect \texttt{\textasciitilde{}/.gitconfig}." in the source becomes "Git will inspect ~{/.gitconfig}." in the generated HTML.

**Comment by Gumnos** [comment]
Same in Chap3: "The command \texttt{git log HEAD\textasciitilde{}1..HEAD} tells Git to show us the git log" becomes "The command git log HEAD~{1..HEAD} tells Git to show us the git log "

**Comment by cbx33** [comment]
% issue has been fixed
I will fix the others as soon as I get time - apologies

**Comment by cbx33** [comment]
tilde also fixed now
