### ISSUE TITLE
In ch7 notes, is "master" an error

### ISSUE THREAD

**Issue by Gumnos** [cbx33/gitt#53]
http://cbx33.github.com/gitt/chap7-6.html reads "git rebase --onto master <branchC> <branchA> <branchB>".  Do you mean "it rebase --onto <branchC> <branchA> <branchB>"?

**Comment by Gumnos** [comment]
grr...github/markdown ate the pseudo-tags.  Trying again, should:

"git rebase --onto master &lt;branchC&gt; &lt;branchA&gt; &lt;branchB&gt;"

be

"git rebase --onto &lt;branchC&gt; &lt;branchA&gt; &lt;branchB&gt;"

**Comment by cbx33** [comment]
Fixed
